# Install udev rules in Linux
RULES_DIR = "/etc/udev/rules.d"

UDEV_RULES = Hash[
  Dir.glob("#{DOTFILES_DIR}/**/*.udev.rules").collect { |file|
    target = File.join(RULES_DIR, file.split('/').last.sub('.udev', ''))
    [file, target]
  }
]

if Dir.exists?(RULES_DIR) && !ENV["WSL_DISTRO_NAME"]
  task :install_udev_rules do
    UDEV_RULES.each do |file, target|
      prompt_install_link(file, target, use_sudo: true)
    end
  end

  task :uninstall_udev_rules do
    UDEV_RULES.each do |file, target|
      uninstall_link(file, target)
    end
  end

  task :install => :install_udev_rules
  task :uninstall => :uninstall_udev_rules
end

# Symlink config to ~/Library/Application Support for macOS
APP_SUPPORT_DIR = File.join(ENV["HOME"], "Library", "Application Support")
QMK_CONFIG_DIR = File.join(DOTFILES_DIR, "qmk", "qmk.config")

if Dir.exists?(APP_SUPPORT_DIR)

  task :install_qmk_config do
    prompt_install_link(QMK_CONFIG_DIR, File.join(APP_SUPPORT_DIR, "qmk"))
  end

  task :uninstall_qmk_config do
    uninstall_link(QMK_CONFIG_DIR, File.join(APP_SUPPORT_DIR, "qmk"))
  end

  task :install => :install_qmk_config
  task :uninstall => :uninstall_qmk_config
end
