RULES_DIR = "/etc/udev/rules.d"

UDEV_RULES = Hash[
  Dir.glob("#{DOTFILES_DIR}/**/*.udev.rules").collect { |file|
    target = File.join(RULES_DIR, file.split('/').last.sub('.udev', ''))
    [file, target]
  }
]

if Dir.exists?(RULES_DIR)
  task :install_udev_rules do
    UDEV_RULES.each do |file, target|
      prompt_install_link(file, target, use_sudo: true)
    end
  end

  task :uninstall_udev_rules do
    UDEV_RULES.each do |file, target|
      uninstall_link(file, target)
    end
  end

  task :install => :install_udev_rules
  task :uninstall => :uninstall_udev_rules
end
