import = [
    "~/.config/alacritty/catppuccin-mocha.toml",
    "~/.config/alacritty/alacritty-os.toml",
]

[font]
normal = { family = "MesloLGMDZ Nerd Font", style = "Regular" }
bold = { family = "MesloLGMDZ Nerd Font", style = "Bold" }
italic = { family = "MesloLGMDZ Nerd Font", style = "Italic" }
builtin_box_drawing = false
