#!/bin/bash
#
# FxOS .userconfig

# Disable First Time User experience
# export NOFTU=1
# echo "NOFTU = ${NOFTU}"

# Enable gaia developer mode
if [[ "`uname`" = "DARWIN" ]]; then
  . "$DOTFILES/b2g_osxconfig"
fi

# export DEVICE_DEBUG=1

# Keeping both debug and non-debug objects
# export GECKO_PATH=${B2G_DIR}/mozilla-inbound
if [[ "$GECKO_PATH" = "" ]]; then
  export GECKO_PATH="$B2G_DIR/gecko"
fi

# export B2G_DEBUG=1

export GECKO_OBJDIR=${GECKO_PATH}/objdir-${DEVICE_NAME}
if [[ "${B2G_DEBUG}" != "0" ]]; then
  export GECKO_OBJDIR=${GECKO_OBJDIR}-debug
fi

echo "************************************************************************"
echo "* Local .userconfig"
echo "************************************************************************"
echo "* B2G_DEBUG:    ${B2G_DEBUG}"
echo "* B2G_DIR:      ${B2G_DIR}"
echo "* DEVICE_DEBUG: ${DEVICE_DEBUG}"
echo "* GECKO_OBJDIR: ${GECKO_OBJDIR}"
echo "* GECKO_PATH:   ${GECKO_PATH}"
echo "************************************************************************"
