#!/usr/bin/env zsh
#
# devcontainer wrapper with support for dotfiles
#

set -e

this_dir="$(cd "$(dirname $0)"; pwd)"
workspace=$(git rev-parse --show-toplevel)

case "$1" in
    up)
        # start container
        CUSTOM_ZSHRC=$HOME/.zshrc \
        devcontainer up \
            --mount "type=bind,source=$DOTFILES,target=/dotfiles" \
            --mount "type=bind,source=$DOTFILES-private,target=/dotfiles-private" \
            --workspace-folder "$workspace"

        # bootstrap env
        devcontainer exec \
            --workspace-folder "$workspace" \
            /dotfiles/bootstrap/bootstrap.sh --devcontainer
        ;;
    shell|exec)
        # run shell
        devcontainer exec --workspace-folder "$workspace" ${@:-zsh}
        ;;
    down)
        # stop container(s). assumes a docker compose workflow for now
        compose_files=()
        for f in $(cat "$workspace/.devcontainer/devcontainer.json" | \
            docker run --rm -i marshallc/jsmin | \
            jq -r '.dockerComposeFile[]' | \
            sed 's#${localWorkspaceFolder}#'$workspace'#'); do
            compose_files+="-f"
            compose_files+=$f
        done

        docker compose "${compose_files[@]}" down
        ;;
esac
